import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // 新增的自定义颜色
        "primary-container": "#9895ff",
        "surface": "#f5f7f9",
        "on-primary-fixed": "#000000",
        "primary-dim": "#4136c8",
        "secondary-custom": "#6a37d4",
        "error": "#b41340",
        "primary-custom": "#4e44d4",
        "tertiary": "#9f00b1",
        "tertiary-dim": "#8b009c",
        "surface-variant": "#d9dde0",
        "surface-bright": "#f5f7f9",
        "on-surface": "#2c2f31",
        "surface-container-high": "#dfe3e6",
        "on-surface-variant": "#595c5e",
        "on-secondary-fixed-variant": "#5f28c8",
        "secondary-container": "#dac9ff",
        "on-primary": "#f5f1ff",
        "on-secondary-container": "#5517bf",
        "on-primary-fixed-variant": "#1c0098",
        "on-error-container": "#510017",
        "inverse-primary": "#8681ff",
        "on-secondary-fixed": "#40009b",
        "surface-container-low": "#eef1f3",
        "surface-dim": "#d0d5d8",
        "background-custom": "#f5f7f9",
        "tertiary-container": "#f785ff",
        "outline": "#747779",
        "secondary-fixed": "#dac9ff",
        "on-tertiary-fixed": "#300037",
        "on-tertiary-fixed-variant": "#670073",
        "tertiary-fixed-dim": "#f26bff",
        "inverse-surface": "#0b0f10",
        "on-error": "#ffefef",
        "on-primary-container": "#15007d",
        "surface-container": "#e5e9eb",
        "on-tertiary-container": "#590063",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#ceb9ff",
        "tertiary-fixed": "#f785ff",
        "primary-fixed": "#9895ff",
        "on-secondary": "#f8f0ff",
        "error-dim": "#a70138",
        "on-tertiary": "#ffeefa",
        "surface-tint": "#4e44d4",
        "secondary-dim": "#5e26c7",
        "outline-variant": "#abadaf",
        "surface-container-highest": "#d9dde0",
        "primary-fixed-dim": "#8985ff",
        "on-background": "#2c2f31",
        "inverse-on-surface": "#9a9d9f",
        "error-container": "#f74b6d"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        "DEFAULT": "1rem", 
        "xl": "2rem", 
        "full": "9999px"
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
